Add Apache Kafka consumer/producer, airports workload
banzaicloud/allspark pull request #14
Opened 2022-05-09 11:06 UTC by hi-im-aren

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
- Add Apache Kafka consumer and producer support
- Add new Airports workload

2022-05-09 12:29 UTC, stoader approved these changes

2022-05-09 13:43 UTC, stoader submitted a review, later dismissed

2022-05-11 20:58 UTC, waynz0r requested changes
The current implementation does not follow the existing pattern for the building blocks. Please re-structure accordingly!

2022-07-07 13:17 UTC, stoader submitted a review, later dismissed

2022-07-07 14:11 UTC, waynz0r approved these changes

2022-07-07 14:12 UTC, merged